theme = "edge"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor]
scrolloff = 0
bufferline = "multiple"


[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 2

[keys.normal]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]

A-d = ["extend_to_line_bounds", "yank", "open_below", "normal_mode", "replace_with_yanked", "collapse_selection"]
