theme = "edge"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor]
scrolloff = 0
bufferline = "multiple"
line-number = 'relative'

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 2

[editor.lsp]
display-messages = true
display-inlay-hints = true

# [editor.whitespace.render]
# newline = "all"

# [editor.whitespace.characters]
# newline = "⏎"




#nbsp = "all"
#nbsp = "⍽"

[keys.normal]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]

A-d = ["extend_to_line_bounds", "yank", "open_below", "normal_mode", "replace_with_yanked", "collapse_selection", "goto_first_nonwhitespace"]

"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
"%" = "match_brackets"
V = ["select_mode", "extend_to_line_bounds"]
# C = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection", "insert_mode"]
D = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection"]
G = ["goto_file_end", "move_line_up"]
esc = ["collapse_selection", "keep_primary_selection", ":w"]
# Search for word under cursor
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]
