
# [[language]]
# name = "python"
# roots = ["pyproject.toml"]
# # formatter = { command = "black", args = ["--quiet", "-"] }
# language-server = { command = "pyright-langserver", args = ["--stdio"] }
# config = {}
# auto-format = true


[[language]]
name = "python"
roots = ["pyproject.toml"]
language-servers = ["pyright", "ruff"]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.ruff]
command = "ruff-lsp"
config = { settings = { run = "onSave" } }
