[theme.overrides]
separator = ""
idle_bg = "#222222"

# separator_bg = "#222222"
# separator_fg = "#222222"
# idle_fg = "#ff00ff"
# alternating_tint_bg = "#222222"
# alternating_tint_fg = "#222222"
# critical_bg = "#222222"
# critical_fg = "#222222"
# good_bg = "#222222"
# good_fg = "#222222"
# info_bg = "#222222"
# info_fg = "#222222"
# separator = "#222222"
# warning_bg = "#222222"
# warning_fg = "#222222"


[icons]
name = "awesome5"
[icons.overrides]
cpu = ""

# [[block]]
# block = "disk_space"
# path = "/"
# info_type = "available"
# unit = "GB"
# interval = 20
# warning = 1.1
# alert = 1.0
# separator=" "


[[block]]
block = "cpu"


[[block]]
block = "memory"
format_mem = "{mem_used}"
display_type = "memory"
interval = 5
warning_mem = 80
critical_mem = 95
icons_format = "| "


[[block]]
block = "net"
format= "{ip} {speed_up:4;K}"
interval = 1
icons_format = "| "



[[block]]
block = "backlight"
device = "intel_backlight"
cycle = [100, 50, 5, 50]
icons_format = "| "


[[block]]
block = "sound"
format = "{volume:5#100}"
icons_format = "  "


[[block]]
block = "time"
interval = 1
format = " %a %d %b %H:%M:%S "
icons_format = ""
