#!/bin/sh
# shellcheck disable=SC1117,SC1083,SC1073,SC1056,SC1072

super + Escape
	pkill -USR1 -x sxhkd


super + f
  firefox

shift + Print
  $HOME/scripts/video/record.sh

Print
  flameshot gui

control + 1
  setxkbmap us
  
control + 2
  setxkbmap ara

super + shift + p
    passmenu

super + a
  bash /root/scripts/dmenu/learn_with_dmenu.sh

super + shift + a
  bash /root/scripts/dmenu/add-word.sh

super + shift + p
  bash ~/scripts/my/dmenu/dmenu_command.sh

super + o
  mpv --loop `xclip -o -sel clip`

super + c 
  wpa_cli reassociate 1
