#!/bin/bash
#history cycle
# autoload -U history-search-end
# zle -N history-beginning-search-backward-end history-search-end
# zle -N history-beginning-search-forward-end history-search-end
# bindkey "^[[A" history-beginning-search-backward-end
# bindkey "^[[B" history-beginning-search-forward-end

# setopt PROMPT_SUBST
PROMPT='$(get_cwd)%f%b '
export HISTFILE=/mega/repo/dotfiles/zsh_history
export HISTSIZE=100000
