#!/bin/sh


shell=bash


enable=add-default-case


# SC2001: See if you can use ${variable//search/replace} instead.
disable=SC2001


# SC2046: Quote this to prevent word splitting.
disable=SC2046

# SC2086: Double quote to prevent globbing and word splitting.
disable=SC2086

# SC2129: Consider using { cmd1; cmd2; } >> file instead of individual redirects.
disable=SC2129

# SC2155: Declare and assign separately to avoid masking return values.
disable=SC2155


# SC2164: Use 'cd ... || exit' or 'cd ... || return' in case cd fails.
disable=SC2164


# SC2317| Command appears to be unreachable.
disable=SC2317


# SC2181| Check exit code directly with e.g. 'if ! mycmd;'
disable=SC2181
