#!/usr/bin/zsh

#
# after compinit and user zsh config
#

#if command -v pazi &>/dev/null; then
#  eval "$(pazi init zsh)" # or 'bash'
#fi


if command -v zoxide >/dev/null 2>&1; then
    eval "$(zoxide init zsh)"
fi

if command -v direnv >/dev/null 2>&1; then
  eval "$(direnv hook zsh)"
fi

if [ -f /home/linuxbrew/.linuxbrew/bin/brew ]; then
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv 2>/dev/null)"
fi

if command -v dbus-launch >/dev/null 2>&1; then
  eval "$(dbus-launch --auto-syntax)"
fi
