#!/bin/bash

root=${1:-ayoub}
LINUX=${1:-void}

mkdir -p $HOME/.config/zsh
mkdir -p $HOME/.texmf $HOME/.cpan/build


if [[ -d $HOME/stow/zsh/init ]];then
    stow --dir=$HOME/stow/zsh --target=$HOME init
fi

if [[ -d $HOME/stow/zsh/universe ]];then
    stow --dir=$HOME/stow/zsh --target=$HOME/.config/zsh universe
fi

case "$LINUX" in
    void)
        if [[ -d $HOME/stow/zsh/void ]];then
            stow --dir=$HOME/stow/zsh --target=$HOME/.config/zsh void
        fi
        if [[ "$root" == "root" ]];then
            [[ -d $HOME/stow/zsh/void-root ]] && stow --dir=$HOME/stow/zsh --target=$HOME/.config/zsh void-root
        else
            [[ -d $HOME/stow/zsh/void-home ]] && stow --dir=$HOME/stow/zsh --target=$HOME/.config/zsh void-home
        fi
        ;;
    *) echo '$LINUX not define' ;;
esac

