#!/bin/zsh

root=${1:-root}

mkdir -p $HOME/.config/zsh
mkdir -p $HOME/.texmf $HOME/.cpan/build


stow --dir=$HOME/stow/zsh --target=$HOME/.config/zsh void
stow --dir=$HOME/stow/zsh --target=$HOME/.config/zsh universe
stow --dir=$HOME/stow/zsh --target=$HOME init

if [[ "$root" = "root" ]];then
    stow --dir=$HOME/stow/zsh --target=$HOME/.config/zsh void-root
else
    stow --dir=$HOME/stow/zsh --target=$HOME/.config/zsh void-home
fi
