export ANDROID_HOME="/opt/sdk/android"
export ANDROID_SDK_HOME="/opt/sdk/android-HOME"
export ANDROID_SDK_root="/opt/sdk/android"
export GRADLE_HOME="/opt/sdk/gradle/gradle-7.1.1"
export GRADLE_USER_HOME="/opt/sdk/gradlec"
export GTK_DEBUG="interactive"
export JAVA_HOME="$HOME/opt/sdk/jdk-18"

export HOWDOI_COLORIZE="1"
export XDEB_PK_ROOT="/tmp/xdeb"

export LANG="en_US.UTF-8"
export LANGUAGE="en_US-UTF-8"
export LC_ADDRESS="POSIX"
export LC_ALL="en_US.UTF-8"
export LC_COLLATE="POSIX"
export LC_CTYPE="POSIX"
export LC_IDENTIFICATION="POSIX"
export LC_MEASUREMENT="POSIX"
export LC_MESSAGES="POSIX"
export LC_MONETARY="POSIX"
export LC_NAME="POSIX"
export LC_NUMERIC="POSIX"
export LC_PAPER="POSIX"
export LC_TELEPHONE="POSIX"
export LC_TIME="POSIX"

export TERM="st-256color"
export TIME="\n%C\n\ttime = %e Sec \n\tCPU  = %P \n\tRAM  = %"


export app8="/projects/flutter/app8"
export app9="/projects/flutter/app9"
export by_linux="/mega/by_linux"
export by_phone="/mega/by_phone"
export c_project="/projects/c"
export download_simple="/mnt/simple/Download"
export js_project="/projects/js"
export p5_project="/projects/p5"
export rust_project="/projects/rust"
export md_project="/projects/md"
export py_project="/projects/py"
export libreoffice_project="/projects/libreoffice"
export flutter_project="/projects/flutter"
export js_project="/projects/javascript"
export javascipt_project="/projects/javascript"
export lua_project="/projects/lua"
export shell_project="/projects/shell"
export tex_project="/projects/tex"

export accadimeque="/mega/cloud/accadimique"
export alias_="$HOME/.config/zsh/my_alias"
export animation1="/projects/flutter/animation1"
export cloud="/mega/cloud"
export codes="/mega/repo/codes"
export function_="$HOME/.config/zsh/my_function"
export kitty="$HOME/.config/kitty/kitty.conf"
export nvimdoc="/usr/local/share/nvim/runtime/doc"
export packerdir="$HOME/.local/share/nvim/site/pack/packer/start"
export path_="$HOME/.config/zsh/all_PATH"
export repo="/mega/repo"
export scripts="$HOME/scripts"
export sv="/var/service"
export template="/xbps-src/all-srcpkgs"
export tmux="$HOME/.tmux.conf"
export todo="/mega/repo/todo"
export whatsapp_doc="/mnt/simple/Android/media/com.whatsapp/WhatsApp/Media/WhatsApp Documents"
export wiki="/mega/repo/wiki"
export xbps_src="/xbps-src/void-packages"
export zshrc="$HOME/.zshrc"

export nvimdir="$HOME/.config/nvim"
export packerdir="$HOME/.local/share/nvim/site/pack/packer/start"
export plugin="$HOME/.config/nvim/after/plugin"
export book="$HOME/book/ayoubelmhamdi.github.io/src"


# export LIBVA_DRIVER_NAME="i965"



export STARSHIP_CONFIG=$HOME/.config/starship/starship.toml
